### ISSUE TITLE
Missing Alphabet 'b' on the Field Labels with Gravity Forms 2.6

### ISSUE THREAD

**Issue by saifsultanc** [gravitywiz/admin-bar-form-manager#2]
## Description
The '_Admin Bar Form Manager_' plugin adds a sequential alphabet to the fields we populate on a form. With Gravity Forms 2.6, the Submit button is rendered as a field and gets auto-assigned the alphabet B as soon as the first field is added to the form (Field A). Thus after field A, the next field we see is field C.

This is how it happens right now:
![before](https://user-images.githubusercontent.com/26293394/162168979-b75a4615-4a2b-477b-92b4-c8ee2806d732.gif)

## Proposed solution
We could add a check to skip adding an alphabet to the Submit button. So after [L175](https://github.com/gravitywiz/admin-bar-form-manager/blob/master/includes/admin-bar-form-manager-new-form.php#L175) on `admin-bar-form-manager-new-form.php`, we could have the following:

```
	if ( type == 'submit' ) {
		return field;
	}
```

With that update, the adding of new fields on the form will not skip the alphabet B. Here is how it will be:

![after](https://user-images.githubusercontent.com/26293394/162169754-b575fdce-3da3-4ee2-8759-75c342f0e5af.gif)

## Additional info
Since I can't push a branch, I can't create a new PR for review. Hence, went ahead to create an issue with the details for you to have a look at @spivurno, @claygriffiths. Thank you!

**Comment by spivurno** [comment]
@saifsultanc Appreciate the suggestion. Makes sense to me! 

@sbassah Could you implement this?

**Comment by saifsultanc** [comment]
Thanks, David @spivurno. Let me know if you want me to fork and send it to you.
